### ISSUE TITLE
The README.md file’s picture links are broken. 

### ISSUE THREAD

**Issue by Drunemeton** [schultzcole/FVTT-Turn-Alert#14]
Tried downloading and renaming to no avail.

**Comment by schultzcole** [comment]
Sorry I didn't respond to this sooner, for some reason I didn't get a notification that this issue was created.

Unfortunately I'm unable to reproduce this issue. The images should be publicly available. I've tried it in Chrome, Firefox and Edge with no issues. What web browser are you using?

GitHub seems to be redirecting to their own domain rather than using the original links when you view on the repo home page. If you try to visit one of the direct links in your browser (https://f002.backblazeb2.com/file/cws-images/FVTT-Turn-Alert/combat_alerts_2.webp) does it still not work?

**Comment by Drunemeton** [comment]
Ah crap kill this issue: It's Safari which doesn't support WebP files. 

When I tried downloading them the filename is so long it gets truncated to: 68747470733a2f2f663030322e6261636b626c617a6562322e636f6d2f66696c652f6377732d696d616765732f465654542d5475726e2d416c6572742f636f6d6261745f747261636b65722e77656270

So I never had an extension to clue me in as to what the problem was. Sorry for the bother.

**Comment by schultzcole** [comment]
Ah, well that's good to know. Thanks for the update!
