### ISSUE TITLE
Suggestion: Allow arguments to a macro alert

### ISSUE THREAD

**Issue by tposney** [schultzcole/FVTT-Turn-Alert#15]
With furnace installed it is possible to pass arguments to macros. It would be good to be able to attach arguments to a turn alert;
i.e.
args: [ ],
and when calling the macro call
macro.execute(...args)

That way when creating a turn alert the state at the time can be recorded for the macro to use.

**Comment by schultzcole** [comment]
Actually this is already kind of an accidental feature, though there isn't any interaction with The Furnace. When the macro is executed, the alert data is in scope and can be accessed as `alert`. And if you create an alert programmatically, you can add extra data to it (in the form of an `args` array or however you want), which can then be accessed by the triggered macro.

Here's an example:

Creation macro:
```js
const alertData = {
    round: 1,
    roundAbsolute: false,
    turnId: game.combat.combatant._id,
    macro: "Arguments Test",
    args: [ "Alice", "Bob", "Charlie" ],
};

TurnAlert.create(alertData);
```

"Arguments Test" macro:
```js
console.log(alert.args); // prints "["Alice", "Bob", "Charlie"]"
```

Note that anything stored in the alert data should be serializable as json because it is just stored in a flag on the combat.

I intend to add `args` as an official property of the alert schema in a future update.

Please let me know if this is not what you're asking for, I might need some more clarification on what you're trying to achieve.

**Comment by tposney** [comment]
That looks perfect. I can see round/turn active effects in my future. Thanks.
