### ISSUE TITLE
Feature Request - Round Alert

### ISSUE THREAD

**Issue by j-schoch** [schultzcole/FVTT-Turn-Alert#32]
Hello!

My previous issues were all discovered while attempting to make a simple "Round X" alert appear in chat at the top of each round.

I can now do that as of 1.5.1, but I have to keep remaking it each combat as alerts are cleared when combat ends.

So I created a macro to help in creating the alert each combat which is pretty good:
```
const alertData = {
    round: 1,
    roundAbsolute: false,
    repeating: {
        frequency: 1,
    },
    macro: "AnnounceRound",
};

TurnAlert.create(alertData);
```

The macro "[AnnounceRound](https://github.com/foundry-vtt-community/macros/pull/139)":
```
const messageContent = `<hr><div style="color: black; font-size: 1.75em; font-weight: bold;">ROUND ${game.combat.round} START</div><hr>`
ChatMessage.create({ content: messageContent });
```

This works just fine, but still requires that I run this macro at the start of combat.  I started wondering if, in addition to announcing each player's turn, this module could also optionally announce the round start or end by default?  It would be very useful for using chat log as combat history.

Either that or maybe allow "pinning" an alert so that it won't clear between combats. (not sure how that would operate outside of "top of round" section)

I realize this is a very specific use-case, and I'm not sure if this fits with your vision for the module, but I figured I'd suggest it. Thanks.

**Comment by schultzcole** [comment]
Hi! Thank you for the earlier bug reports and your interest in Turn Alert. I'm sorry to say I don't plan on implementing something like this directly. My preference for Turn Alert would be to be as minimal as possible while giving users the tools they need to make their own alerts, rather than adding its own opinionated alerts by default.

That being said, as I mentioned, I want to make sure the tools are available for you to do what you want. There is a way to achieve the results you want, albeit it does require a bit of initial setup. Essentially we'll create a "world script", which will add a new alert to any combat when it is created.

First, you'll need to create a new file in your world's directory (i.e. in `<your foundry user data>\Data\worlds\<your world>`) called `roundAlert.js`. In this file, paste the following code:

```js
Hooks.on("createCombat", (combat) => {
    const alertData = {
        combatId: combat.id,
        round: 1,
        roundAbsolute: false,
        repeating: {
            frequency: 1,
        },
        label: "Announce Round",
        macro: "AnnounceRound",
    };

    TurnAlert.create(alertData);
});
```

Finally, open the `world.json` file in the same folder and add the script to the "esmodules" array. It should look like this: `"esmodules": ["roundAlert.js"],`. The "esmodules" key should already exist, but if it does not, you can add it in just after "compatibleCoreVersion".

This is unfortunately more difficult to edit, although you can of course change your "AnnounceRound" macro to do whatever you wish at the top of the round.

I hope this solution is sufficient for your purposes, if somewhat less convenient than what you were hoping for.

**Comment by j-schoch** [comment]
I'm new to scripting in Foundry but I can definitely work with this!

Thanks a lot for the quick and detailed response.
