### ISSUE TITLE
How do I...

### ISSUE THREAD

**Issue by Motara7** [schultzcole/FVTT-Turn-Alert#34]
This module is a "must have" for running Pathfinder 1e! Thank you!

I'm working with your Basic Macro and I was wondering if it's possible to change "round: 1," to "round: caster level of selected token." I am very inexperienced with js. So, I have no idea what would be entailed with this. If it's too involved, I'll just keep using the macro that opens the dialog box, but having it pull that number automatically would save people a few steps if it's possible.

**Comment by schultzcole** [comment]
Hi Motara, thanks for the question. Yes, this is certainly possible, you'll want to do something like

```js
round: token.actor.data.data.spells.spellbooks.primary.cl.total
```

I must admit that I don't know too much about PF1e so that might be incomplete, especially for multi-classed characters. But I hope this helps. I'm going to close this issue but let me know if you need something more.
